### PR TITLE
Add fonts with different font-weights

### PR DESCRIPTION
**Pull request by EugeneBalabai**
Based on: https://github.com/MrRio/jsPDF/pull/3036

Now users can use any combination of font-weight and font-style

### CODE REVIEW

**Review by HackbrettXXX — CHANGES_REQUESTED** [review]
Thanks for the PR!

I like this approach, because it remains compatible with jsPDF@<2.3.0. However, I think we still should implement it differently: we should pass font style and font weight as separate arguments to `setFont`. This way, we let jsPDF do the heavy lifting of combining them (which is more of an implementation detail, anyway). It would also be more futureproof, in case jsPDF improves the algorithm that matches a combination of font style and font weight with the available fonts.

In order to remain compatible with jsPDF@<2.3.0 we could switch between the old and new code paths depending on the `jsPDF.version` property.

**Comment by EugeneBalabai** [comment]
Hey @HackbrettXXX 

Thanks for review
yep, we can pass font-weight as separate arguments to `setFont` and I will do it (a bit later). But what about `findFirstAvailableFontFamily`? We still need to combine font style and font-weight with the same algorithm as jsPDF to get the correct fontFamily. Or do you have any ideas on how we can solve this?

**Comment by HackbrettXXX** [comment]
Ah, good catch! Unfortunately, I don't have a better idea for `findFirstAvailableFontFamily`. I guess, If we're forced to combine font style/weight manually anyway, we can just take your initial implementation.

Could you have a look at the failing tests? Seems like some test cases produce different results now. The new results are probably correct, though. Please update the reference files in that case.

**Comment by HackbrettXXX** [comment]
I've added some changes: the function for combining fonts was actually not correct in jsPDF. I've fixed it there (https://github.com/MrRio/jsPDF/pull/3217). The fix will be released with jsPDF@2.4.0. I've added a version switch to svg2pdf, so it will work with both jsPDF versions. The tests will fail until we update to jsPDF@2.4.0. We can do so, once it's released.

**Comment by EugeneBalabai** [comment]
@HackbrettXXX great job! Do you know when it will release?

**Comment by HackbrettXXX** [comment]
Hopefully soon ;)

**Review by HackbrettXXX — APPROVED** [review]

**Pull request merged**
